apiVersion: v3
name: argo-cd-configs
description: | 
  Main Argo CD deployment for the RSO 2024 Group 12 project.
  Only used by ArgoCD itself to deploy new configs for it.
  Terraform evaluates the manifest with helm and then pushes it into the cluster.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.1"

sources:
  - https://github.com/RSO-2024-Group-12/infra
  # Source of chart
  - oci://ghcr.io/rso-2024-group-12/charts/argo-cd-configs

# dependencies:
#   - name: argo-cd
#     version: 9.2.4
#     repository: https://argoproj.github.io/argo-helm
#     alias: parent-argo-cd
  