apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ include "nakupify-platform.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "nakupify-platform.labels" . | nindent 4 }}
spec:
  db:
    vendor: postgres
    poolInitialSize: 2
    poolMinSize: 2
    poolMaxSize: 10 # more connections needed to avoid the "acquisition timeout"
  env:
    - name: KC_DB_URL
      secret:
        name: {{ .Release.Name }}-pguser-{{ (index .Values.postgresDb.users 0).name }}
        key: "jdbc-uri"
    - name: "QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT" # or perhaps this works?
      value: "10s" 
  http:
    httpEnabled: true
    httpPort: 8180
    #httpsPort: 8543
    # tlsSecret: my-tls-secret
  hostname:
    hostname: "http://localhost:8180/"
    admin: "http://localhost:8180/"
    strict: false
    backchannelDynamic: true
  features:
    enabled:
      - docker
      - authorization
      - admin
    disabled:
      - step-up-authentication
  transaction:
    xaEnabled: false
