{{- if .Values.useLookup -}}
{{- $svc := lookup "v1" "Service" .Release.Namespace .Values.db.serviceName -}}
{{- if not $svc -}}
{{- fail (printf "Service %s not found in namespace %s" .Values.db.serviceName .Release.Namespace) -}}
{{- end -}}
{{- set .Values.db "hostAddress" (printf "%s.%s" $svc.metadata.name $svc.metadata.namespace) -}}
{{- set .Values.db "hostPort" (index $svc.spec.ports 0).port -}}
{{- else -}}
{{- required ".Values.db.hostAddress is required!" .Values.db.hostAddress -}}
{{- required ".Values.db.hostPort is required!" .Values.db.hostPort -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db-init.secretName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hooks": pre-install
    "helm.sh/hook-weight": "-1"
    # "helm.sh/hook-delete-policy": hook-failed
type: Opaque
data:
  user: {{ .Values.db.user | b64enc }}
  password: {{ default (randAlphaNum 32) .Values.db.password | b64enc }}
  database: {{ .Values.db.database | b64enc }}
  schema: {{ .Values.db.schema | b64enc }}
  host: {{ .Values.db.hostAddress | b64enc }}
  port: {{ .Values.db.hostPort | b64enc }}
  uri: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.db.user .Values.db.password .Values.db.hostAddress .Values.db.hostPort .Values.db.database | b64enc }}
  jdbc-uri: {{ printf "jdbc:postgresql://%s:%s/%s?user=%s&password=%s" .Values.db.hostAddress .Values.db.hostPort .Values.db.database .Values.db.user .Values.db.password | b64enc }}