apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db-init.secretName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hooks": pre-install
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
  user: {{ .Values.db.user | b64enc }}
  {{- $password := default (randAlphaNum 32) .Values.db.password }}
  password: {{ $password | b64enc }}
  database: {{ .Values.db.database | b64enc }}
  schema: {{ .Values.db.schema | b64enc }}
  host: {{ .Values.db.hostAddress | b64enc }}
  port: {{ printf "%s" .Values.db.hostPort | b64enc }}
  uri: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.db.user (urlquery $password) .Values.db.hostAddress .Values.db.hostPort .Values.db.database | b64enc }}
  jdbc-uri: {{ printf "jdbc:postgresql://%s:%s/%s?user=%s&password=%s" .Values.db.hostAddress .Values.db.hostPort .Values.db.database .Values.db.user (urlquery $password) | b64enc }}