apiVersion: v1
kind: Secret
metadata:
  name: github-org-creds
  namespace: {{ .Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: {{ required "org.url is required" .Values.org.url | quote }}
  type: helm
  githubAppID: {{ required "org.githubAppID is required" .Values.org.githubAppID | quote }}
  githubAppInstallationID: {{ required "org.githubAppInstallationID is required" .Values.org.githubAppInstallationID | quote }}
  githubAppEnterpriseBaseUrl: {{ required "org.githubAppEnterpriseBaseUrl is required" .Values.org.githubAppEnterpriseBaseUrl | quote }}
{{- if .Values.org.privateKey }}
  githubAppPrivateKey: |
{{ .Values.org.privateKey }}
{{- else if .Values.org.privateKeyFile}}
  githubAppPrivateKey: |
{{ .Files.Get .Values.org.privateKeyFile | indent 4 }}
{{- else }}
    {{- required "org.privateKey or org.privateKeyFile is required" .Values.org.privateKey }}
{{- end }}
  