apiVersion: v1
kind: Secret
metadata:
  name: github-app-secret
  namespace: {{ .Release.Namespace }}
  # annotations:
  #   "helm.sh/hook": pre-install,pre-upgrade
  #   "helm.sh/hook-weight": "-1"
type: Opaque
data:
  app-id: {{ .Values.githubAppInfo.id | b64enc }}
  installation-id: {{ .Values.githubAppInfo.installationId | b64enc }}
  private-key: {{ .Values.githubAppInfo.privateKey | b64enc }}
  enterprise-base-url: {{ .Values.githubAppInfo.enterpriseBaseUrl | b64enc }}