{{- range $key, $cred := .Values.credentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-repo-cred-{{ $key }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}-repo-cred-{{ $key }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: argo-cd-repo-cred-secrets
{{- if not (eq $cred.type "github" ) }}
    githubTokenRefresh: "true"
{{- end }}
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
{{ if eq $cred.type "helm" -}}
data:
  username: {{ "RSO-2024-Group-12" | b64enc }}
  {{- include "my-argo-cd.b64enc" $cred | nindent 2 }}
{{ else if eq $cred.type "github" -}}
{{ $cred := set $cred "type" "git" -}}
stringData:
  url: {{ $cred.url | required "url is required" }}
  {{- $cred := omit $cred "url" -}}
  {{- toYaml $cred | nindent 2 }}
  {{- include "my-argo-cd.secrets.githubAppData" $.Values.githubAppInfo | nindent 2 }}
{{- else -}}
{{- fail "Unsupported credential type: " $cred.type -}}
{{- end }}
---
{{- end -}}
