{{- range $key, $value := .Values.repositories -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-repo-{{ $key }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}-repo-{{ $key }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: argo-cd-repo-secrets
    argocd.argoproj.io/secret-type: repository
{{- if not (eq $value.type "github" ) }}
    githubTokenRefresh: "true"
{{- end }}
type: Opaque
{{ if eq $value.type "helm" -}}
data:
  name: {{ $key | required "name is required" | b64enc }}
  username: {{ "RSO-2024-Group-12" | b64enc }}
  {{- include "my-argo-cd.b64enc" $value | nindent 2 }}
{{ else if eq $value.type "github" -}}
{{ $value := set $value "type" "git" -}}
stringData:
  name: {{ $key | required "name is required" | quote }}
  url: {{ $value.url | required "url is required" }}
  {{- $value := omit $value "url" -}}
  {{- toYaml $value | nindent 2 }}
  {{- include "my-argo-cd.secrets.githubAppData" $.Values.githubAppInfo | nindent 2 }}
{{- else -}}
{{- fail "Unsupported repository type: " $value.type -}}
{{- end }}
---
{{- end -}}