name: Publish DB-init Helm Chart

on:
  push:
    tags:
      - 'chart-db-init-*'   # example: chart-myapp-0.1.0

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          helm registry login ghcr.io \
            --username ${{ github.actor }} \
            --password-stdin

      - name: Package chart
        run: |
          helm package -u ./db-init

      - name: Push chart to GHCR
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          helm push *.tgz oci://ghcr.io/$OWNER